services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Install PHP 'zip' extension to allow installing Backdrop modules.
        - docker-php-ext-install zip
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT $DOCROOT
      update:
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/settings.local.php
        # Create and set the config directories.
        - mkdir $TUGBOAT_ROOT/files/config_$TUGBOAT_PREVIEW_ID
        - mkdir $TUGBOAT_ROOT/files/config_$TUGBOAT_PREVIEW_ID/active
        - mkdir $TUGBOAT_ROOT/files/config_$TUGBOAT_PREVIEW_ID/staging
        - echo "\$config_directories['active'] = 'files/config_$TUGBOAT_PREVIEW_ID/active';" >> $TUGBOAT_ROOT/settings.local.php
        - echo "\$config_directories['staging'] = 'files/config_$TUGBOAT_PREVIEW_ID/staging';" >> $TUGBOAT_ROOT/settings.local.php
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data $TUGBOAT_ROOT
        - find $TUGBOAT_ROOT/files $TUGBOAT_ROOT/layouts $TUGBOAT_ROOT/modules $TUGBOAT_ROOT/themes -type d -exec chmod 2775 {} \;
        - find $TUGBOAT_ROOT/files $TUGBOAT_ROOT/layouts $TUGBOAT_ROOT/modules $TUGBOAT_ROOT/themes -type f -exec chmod 0664 {} \;
        # Install Backdrop.
        - cd $TUGBOAT_ROOT && ./core/scripts/install.sh --db-url=mysql://tugboat:tugboat@mariadb/tugboat --account-pass=password
        # Fix config permissions after install.
        - chown -R www-data:www-data $TUGBOAT_ROOT/files/config_$TUGBOAT_PREVIEW_ID/active
        - find $TUGBOAT_ROOT/files/config_$TUGBOAT_PREVIEW_ID/active -type f -exec chmod 0664 {} \;
        # Post a comment to the PR.
        - cd $TUGBOAT_ROOT && ./.tugboat/post-comment.sh
  mariadb:
    image: tugboatqa/mariadb:latest
    commands:
      init:
        # Configure database for UTF-8: https://api.backdropcms.org/database-configuration#utf8mb4
        - echo "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true" >> /etc/mysql/conf.d/utf8mb.conf
