services:
  php:
    # See: https://github.com/TugboatQA/dockerfiles/blob/main/php/TAGS.md
    image: tugboatqa/php:8.3-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Install PHP 'zip' extension to allow installing Backdrop modules.
        - apt update && apt install -y libzip-dev
        - docker-php-ext-install zip
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT $DOCROOT
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/settings.local.php
        # Create the config directories.
        - mkdir $TUGBOAT_ROOT/files/config
        - mkdir $TUGBOAT_ROOT/files/config/active
        - mkdir $TUGBOAT_ROOT/files/config/staging
      update:
        # Set appropriate file permissions/ownership for installer/self-updater.
        - cd $TUGBOAT_ROOT && chown -R www-data:www-data files layouts modules themes core
        - cd $TUGBOAT_ROOT && find files layouts modules themes core -type d -exec chmod 2775 {} \;
        - cd $TUGBOAT_ROOT && find files layouts modules themes core -type f -exec chmod 0664 {} \;
      build:
        # Delete previous comments in the PR.
        - cd $TUGBOAT_ROOT/.tugboat && ./delete-comments.sh
        # Clear out active config (needed when rebuilding/reinstalling).
        - find $TUGBOAT_ROOT/files/config/active -mindepth 1 -delete
        # Generate and store a random password for the admin user.
        - openssl rand -hex 6 > $TUGBOAT_ROOT/.tugboat/password
        # Install Backdrop.
        - chmod +x $TUGBOAT_ROOT/core/scripts/install.sh
        - cd $TUGBOAT_ROOT && ./core/scripts/install.sh --db-url=mysql://tugboat:tugboat@mariadb/tugboat --account-pass=`cat .tugboat/password`
        # Fix config permissions after install.
        - chown -R www-data:www-data $TUGBOAT_ROOT/files/config/active
        - find $TUGBOAT_ROOT/files/config/active -type f -exec chmod 0664 {} \;
        # Set an expiration date/time for the preview.
        - cd $TUGBOAT_ROOT/.tugboat && ./set-expiry.sh
        # Post a comment in the PR.
        - cd $TUGBOAT_ROOT/.tugboat && ./post-comment.sh
  mariadb:
    image: tugboatqa/mariadb:lts
    commands:
      init:
        # Configure database for UTF-8: https://docs.backdropcms.org/documentation/database-configuration#utf8mb4
        - echo "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true" >> /etc/mysql/conf.d/utf8mb.conf
      build:
        # Drop and re-create the database (needed when rebuilding/reinstalling).
        - mariadb-admin -f drop tugboat && mariadb-admin create tugboat
